/*©monty*/
window.onload=function(){search[0].style.color="grey";search[0].value="search...";search[0].onclick=function(){if(search[0].value=="search...")search[0].value="",search[0].style.color="black"};search[0].onblur=function(){if(search[0].value=="")search[0].value="search...",search[0].style.color="grey"};search.onsubmit=function(){return search[0].value.length==0||search[0].value=="search..."?!1:!0};if(window.location.hash){var a=window.location.href.slice(0,-window.location.hash.length);a=="http://dlzip.in/edit_info.py"&&
d();a=="http://dlzip.in/login.py"&&e();if(a=="http://dlzip.in/signup.py")document.forms[1].onsubmit=function(){return f()};if(a=="http://dlzip.in/contactme.py"){document.forms[1].onsubmit=function(){return g()};a=document.getElementsByClassName("contactme");for(i=0;i<a.length;i++)a[i].style.borderColor="grey",a[i].style.borderWidth="thin";expand=document.getElementById("textarea_contact");expand.style.color="grey";erase_email_contact=document.getElementById("email_contact");erase_email_contact.onclick=
function(){h()};erase_email_contact.onblur=function(){k()};erase_email_contact.style.color="grey";erase_email_contact.value="email@example.com"}}else if(window.location.search){a=window.location.href.slice(0,-window.location.search.length);a=="http://dlzip.in/edit_info.py"&&d();if(a=="http://dlzip.in/login.py")document.forms[1].onsubmit=function(){return f()};if(a=="http://dlzip.in/signup.py")document.forms[1].onsubmit=function(){return f()};if(a=="http://dlzip.in/contactme.py"){document.forms[1].onsubmit=
function(){return g()};a=document.getElementsByClassName("contactme");for(i=0;i<a.length;i++)a[i].style.borderColor="grey",a[i].style.borderWidth="thin";expand=document.getElementById("textarea_contact");expand.style.color="grey";erase_email_contact=document.getElementById("email_contact");erase_email_contact.onclick=function(){h()};erase_email_contact.onblur=function(){k()};erase_email_contact.style.color="grey";erase_email_contact.value="email@example.com"}}else{window.location=="http://dlzip.in/edit_info.py"&&
d();window.location=="http://dlzip.in/login.py"&&e();if(window.location=="http://dlzip.in/signup.py")document.forms[1].onsubmit=function(){return f()};if(window.location=="http://dlzip.in/index.py"){var b=document.getElementById("show_all");b.onclick=function(){b.getAttribute("href")=="Javascript:;"?b.setAttribute("href","showall.py"):b.setAttribute("href","Javascript:;")};setTimeout(ajax_call,1E4)}if(window.location=="http://dlzip.in/contactme.py"){document.forms[1].onsubmit=function(){return g()};
a=document.getElementsByClassName("contactme");for(i=0;i<a.length;i++)a[i].style.borderColor="grey",a[i].style.borderWidth="thin";expand=document.getElementById("textarea_contact");expand.style.color="grey";expand.onclick=function(){expand.style.color="black";expand.style.borderColor="blue";expand.borderBottomWidth="thin";expand.rows="8";if(expand.value==="Message Body....")expand.value=""};expand.onblur=function(){expand.style.borderColor="grey";expand.value===""?(expand.style.color="grey",expand.value=
"Message Body....",expand.rows="5"):expand.rows="8"};erase_email_contact=document.getElementById("email_contact");erase_email_contact.onclick=function(){h()};erase_email_contact.onblur=function(){k()};erase_email_contact.style.color="grey";erase_email_contact.value="email@example.com"}}};
function h(){erase_email_contact.style.borderColor="blue";erase_email_contact.borderBottomWidth="thin";erase_email_contact.style.borderColor="blue";if(erase_email_contact.value==="email@example.com")erase_email_contact.style.color="black",erase_email_contact.value=""}function k(){erase_email_contact.style.borderColor="grey";if(erase_email_contact.value==="")erase_email_contact.style.color="grey",erase_email_contact.value="email@example.com"}function l(){return f()}
function f(){var a=signupForm,b;a[1].value.length>0?(document.getElementById("signup_name_notify").innerHTML="",b=!0):(document.getElementById("signup_name_notify").innerHTML="ERROR!!",b=!1);var c;a[3].value.length>=8?(document.getElementById("signup_pwd_notify").innerHTML="",c=!0):(document.getElementById("signup_pwd_notify").innerHTML="ERROR!!",c=!1);var j;a[3].value===a[4].value?(document.getElementById("signup_pwdd_notify").innerHTML="",j=!0):(document.getElementById("signup_pwdd_notify").innerHTML=
"ERROR!!",j=!1);a[5].value.length>8?(document.getElementById("signup_email_notify").innerHTML="",a=!0):(document.getElementById("signup_email_notify").innerHTML="ERROR!!",a=!1);return l&&b&&c&&a&&a&&j?!0:!1}function d(){document.forms[1].onsubmit=function(){var a;a=document.getElementsByName("email_check")[0];document.getElementsByName("name_check")[0].checked!==!0&&a.checked!==!0?(document.getElementById("edit_profile_notify").innerHTML="please select a checkbox ",a=!1):a=!0;return a}}
function e(){document.forms[1].onsubmit=function(){return m()}}function m(){var a=document.getElementById("login_email").value,b=document.getElementById("login_pwd").value;return a.length===0&&b.length===0?(document.getElementById("login_notify").innerHTML="email/password fields are empty",!1):a.length===0?(document.getElementById("login_notify").innerHTML="email field is empty",!1):b.length===0?(document.getElementById("login_notify").innerHTML="password field is empty",!1):!0}
function g(){var a=document.getElementById("email_contact").value,b=document.getElementById("subject_contact").value,c=document.getElementById("textarea_contact").value;return a.length===0||a=="email@example.com"||b.length===0||c.length===0||c=="Message Body...."?(document.getElementById("contactme_notify").innerHTML="Please Fill The Form Correctly",!1):!0};function notify(){var a=document.getElementById("status");a.style.backgroundColor="#fff1a8";po=setInterval(timer,1E3);a.innerHTML=" Your download will begin in <span id='timeri'>5</span> seconds.. ";setTimeout(function(){a.innerHTML="";a.style.backgroundColor="#fff"},5E3)}function err(){confirm("Go to LogIn page")?location.assign("http://dlzip.in/login.py"):alert("okay")};